const StockId = require('../models/AutoGeneratedStockId');

module.exports.findLastStockId = async () => {
	const lastStockId = await StockId.findOne().sort({ createdAt: -1 });
	return lastStockId?.stockId;
}