const mongoose = require('mongoose');

const autoGeneratedBarcodeSchema = new mongoose.Schema(
	{
		barcodeNumber: String,
		productId: {
			type: mongoose.SchemaTypes.ObjectId,
			ref: 'product'
		}
	},
	{ timestamps: true }
);


module.exports = mongoose.model('auto-generated-barcode', autoGeneratedBarcodeSchema);